import type { GameSpace } from '../types';

export default {
  activityLog: [],
  creator: '',
  elements: [
    {
      height: 440,
      lock: {
        config: true,
        position: true,
        remove: true,
        rotation: true,
        size: true,
        wals: true,
      },
      rotation: 0,
      type: 'Image',
      url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/25/Chessboard_green_squares.svg/512px-Chessboard_green_squares.svg.png',
      uuid: 'c41c01f0-a037-11ef-8b06-8597ca08db5f',
      version: 1,
      wals: [],
      width: 468,
      x: 1.5,
      y: 1,
      z: 1,
    },
    {
      display: {
        mode: 'emoji',
        value: '⚫️',
      },
      height: 30,
      lock: {
        config: true,
        position: false,
        remove: false,
        rotation: false,
        size: false,
        wals: false,
      },
      rotation: 0,
      type: 'Piece',
      uuid: 'd1da6110-a037-11ef-8b06-8597ca08db5f',
      version: 1,
      wals: [],
      width: 30,
      x: -134.5,
      y: -191,
      z: 4,
    },
    {
      display: {
        mode: 'emoji',
        value: '⚫️',
      },
      height: 30,
      lock: {
        config: true,
        position: false,
        remove: false,
        rotation: false,
        size: false,
        wals: false,
      },
      rotation: 0,
      type: 'Piece',
      uuid: 'e82307b0-a037-11ef-8b06-8597ca08db5f',
      version: 1,
      wals: [],
      width: 30,
      x: -24.5,
      y: -190,
      z: 6,
    },
    {
      display: {
        mode: 'emoji',
        value: '⚫️',
      },
      height: 30,
      lock: {
        config: true,
        position: false,
        remove: false,
        rotation: false,
        size: false,
        wals: false,
      },
      rotation: 0,
      type: 'Piece',
      uuid: 'ed197a10-a037-11ef-8b06-8597ca08db5f',
      version: 1,
      wals: [],
      width: 30,
      x: 87.5,
      y: -189,
      z: 8,
    },
    {
      display: {
        mode: 'emoji',
        value: '⚫️',
      },
      height: 30,
      lock: {
        config: true,
        position: false,
        remove: false,
        rotation: false,
        size: false,
        wals: false,
      },
      rotation: 0,
      type: 'Piece',
      uuid: 'f1ae6b80-a037-11ef-8b06-8597ca08db5f',
      version: 1,
      wals: [],
      width: 30,
      x: 196.5,
      y: -189,
      z: 10,
    },
    {
      display: {
        mode: 'emoji',
        value: '⚫️',
      },
      height: 30,
      lock: {
        config: true,
        position: false,
        remove: false,
        rotation: false,
        size: false,
        wals: false,
      },
      rotation: 0,
      type: 'Piece',
      uuid: 'f46d8b80-a037-11ef-8b06-8597ca08db5f',
      version: 1,
      wals: [],
      width: 30,
      x: -188.5,
      y: -135,
      z: 11,
    },
    {
      display: {
        mode: 'emoji',
        value: '⚫️',
      },
      height: 30,
      lock: {
        config: true,
        position: false,
        remove: false,
        rotation: false,
        size: false,
        wals: false,
      },
      rotation: 0,
      type: 'Piece',
      uuid: 'f8c9b9b0-a037-11ef-8b06-8597ca08db5f',
      version: 1,
      wals: [],
      width: 30,
      x: -81.5,
      y: -135,
      z: 13,
    },
    {
      display: {
        mode: 'emoji',
        value: '⚫️',
      },
      height: 30,
      lock: {
        config: true,
        position: false,
        remove: false,
        rotation: false,
        size: false,
        wals: false,
      },
      rotation: 0,
      type: 'Piece',
      uuid: 'fe250860-a037-11ef-8b06-8597ca08db5f',
      version: 1,
      wals: [],
      width: 30,
      x: 28.5,
      y: -134,
      z: 15,
    },
    {
      display: {
        mode: 'emoji',
        value: '⚫️',
      },
      height: 30,
      lock: {
        config: true,
        position: false,
        remove: false,
        rotation: false,
        size: false,
        wals: false,
      },
      rotation: 0,
      type: 'Piece',
      uuid: '021b6fe0-a038-11ef-8b06-8597ca08db5f',
      version: 1,
      wals: [],
      width: 30,
      x: 142.5,
      y: -135,
      z: 17,
    },
    {
      display: {
        mode: 'emoji',
        value: '🔴',
      },
      height: 30,
      lock: {
        config: true,
        position: false,
        remove: false,
        rotation: false,
        size: false,
        wals: false,
      },
      rotation: 0,
      type: 'Piece',
      uuid: '1339c2e0-a038-11ef-8b06-8597ca08db5f',
      version: 1,
      wals: [],
      width: 30,
      x: -187.5,
      y: 192,
      z: 20,
    },
    {
      display: {
        mode: 'emoji',
        value: '🔴',
      },
      height: 30,
      lock: {
        config: true,
        position: false,
        remove: false,
        rotation: false,
        size: false,
        wals: false,
      },
      rotation: 0,
      type: 'Piece',
      uuid: '174b5380-a038-11ef-8b06-8597ca08db5f',
      version: 1,
      wals: [],
      width: 30,
      x: -78.5,
      y: 194,
      z: 22,
    },
    {
      display: {
        mode: 'emoji',
        value: '🔴',
      },
      height: 30,
      lock: {
        config: true,
        position: false,
        remove: false,
        rotation: false,
        size: false,
        wals: false,
      },
      rotation: 0,
      type: 'Piece',
      uuid: '1b4b09d0-a038-11ef-8b06-8597ca08db5f',
      version: 1,
      wals: [],
      width: 30,
      x: 30.5,
      y: 196,
      z: 24,
    },
    {
      display: {
        mode: 'emoji',
        value: '🔴',
      },
      height: 30,
      lock: {
        config: true,
        position: false,
        remove: false,
        rotation: false,
        size: false,
        wals: false,
      },
      rotation: 0,
      type: 'Piece',
      uuid: '1f9117f0-a038-11ef-8b06-8597ca08db5f',
      version: 1,
      wals: [],
      width: 30,
      x: 138.5,
      y: 194,
      z: 26,
    },
    {
      display: {
        mode: 'emoji',
        value: '🔴',
      },
      height: 30,
      lock: {
        config: true,
        position: false,
        remove: false,
        rotation: false,
        size: false,
        wals: false,
      },
      rotation: 0,
      type: 'Piece',
      uuid: '2545f850-a038-11ef-8b06-8597ca08db5f',
      version: 1,
      wals: [],
      width: 30,
      x: -136.5,
      y: 139,
      z: 29,
    },
    {
      display: {
        mode: 'emoji',
        value: '🔴',
      },
      height: 30,
      lock: {
        config: true,
        position: false,
        remove: false,
        rotation: false,
        size: false,
        wals: false,
      },
      rotation: 0,
      type: 'Piece',
      uuid: '2960b0b0-a038-11ef-8b06-8597ca08db5f',
      version: 1,
      wals: [],
      width: 30,
      x: -24.5,
      y: 139,
      z: 31,
    },
    {
      display: {
        mode: 'emoji',
        value: '🔴',
      },
      height: 30,
      lock: {
        config: true,
        position: false,
        remove: false,
        rotation: false,
        size: false,
        wals: false,
      },
      rotation: 0,
      type: 'Piece',
      uuid: '2cbc10b0-a038-11ef-8b06-8597ca08db5f',
      version: 1,
      wals: [],
      width: 30,
      x: 86.5,
      y: 141,
      z: 33,
    },
    {
      display: {
        mode: 'emoji',
        value: '🔴',
      },
      height: 30,
      lock: {
        config: true,
        position: false,
        remove: false,
        rotation: false,
        size: false,
        wals: false,
      },
      rotation: 0,
      type: 'Piece',
      uuid: '3046be10-a038-11ef-8b06-8597ca08db5f',
      version: 1,
      wals: [],
      width: 30,
      x: 196.5,
      y: 138,
      z: 35,
    },
    {
      height: 152,
      lock: {
        config: false,
        position: false,
        remove: false,
        rotation: false,
        size: false,
        wals: false,
      },
      rotation: 0,
      showEmptyPlayersSlots: true,
      showTimers: true,
      turnsLog: [],
      type: 'TurnTracker',
      uuid: 'b5ec7f90-a039-11ef-8b06-8597ca08db5f',
      version: 2,
      wals: [],
      width: 198,
      x: 327.5,
      y: 3,
      z: 36,
    },
    {
      display: {
        mode: 'emoji',
        value: '🔴',
      },
      height: 30,
      lock: {
        config: true,
        position: false,
        remove: false,
        rotation: false,
        size: false,
        wals: false,
      },
      rotation: 0,
      type: 'Piece',
      uuid: '91b10cf0-00dc-11f0-af54-89c0197358c6',
      version: 1,
      wals: [],
      width: 30,
      x: -192.5,
      y: 85,
      z: 37,
    },
    {
      display: {
        mode: 'emoji',
        value: '🔴',
      },
      height: 30,
      lock: {
        config: true,
        position: false,
        remove: false,
        rotation: false,
        size: false,
        wals: false,
      },
      rotation: 0,
      type: 'Piece',
      uuid: '93d7bd80-00dc-11f0-af54-89c0197358c6',
      version: 1,
      wals: [],
      width: 30,
      x: 138.5,
      y: 88,
      z: 38,
    },
    {
      display: {
        mode: 'emoji',
        value: '🔴',
      },
      height: 30,
      lock: {
        config: true,
        position: false,
        remove: false,
        rotation: false,
        size: false,
        wals: false,
      },
      rotation: 0,
      type: 'Piece',
      uuid: '93edb680-00dc-11f0-af54-89c0197358c6',
      version: 1,
      wals: [],
      width: 30,
      x: 26.5,
      y: 88,
      z: 39,
    },
    {
      display: {
        mode: 'emoji',
        value: '🔴',
      },
      height: 30,
      lock: {
        config: true,
        position: false,
        remove: false,
        rotation: false,
        size: false,
        wals: false,
      },
      rotation: 0,
      type: 'Piece',
      uuid: '94053620-00dc-11f0-af54-89c0197358c6',
      version: 1,
      wals: [],
      width: 30,
      x: -79.5,
      y: 86,
      z: 40,
    },
    {
      display: {
        mode: 'emoji',
        value: '⚫️',
      },
      height: 30,
      lock: {
        config: true,
        position: false,
        remove: false,
        rotation: false,
        size: false,
        wals: false,
      },
      rotation: 0,
      type: 'Piece',
      uuid: '99930680-00dc-11f0-af54-89c0197358c6',
      version: 1,
      wals: [],
      width: 30,
      x: 193.5,
      y: -83,
      z: 41,
    },
    {
      display: {
        mode: 'emoji',
        value: '⚫️',
      },
      height: 30,
      lock: {
        config: true,
        position: false,
        remove: false,
        rotation: false,
        size: false,
        wals: false,
      },
      rotation: 0,
      type: 'Piece',
      uuid: '99adba70-00dc-11f0-af54-89c0197358c6',
      version: 1,
      wals: [],
      width: 30,
      x: 85.5,
      y: -81,
      z: 42,
    },
    {
      display: {
        mode: 'emoji',
        value: '⚫️',
      },
      height: 30,
      lock: {
        config: true,
        position: false,
        remove: false,
        rotation: false,
        size: false,
        wals: false,
      },
      rotation: 0,
      type: 'Piece',
      uuid: '99cb5490-00dc-11f0-af54-89c0197358c6',
      version: 1,
      wals: [],
      width: 30,
      x: -24.5,
      y: -81,
      z: 43,
    },
    {
      display: {
        mode: 'emoji',
        value: '⚫️',
      },
      height: 30,
      lock: {
        config: true,
        position: false,
        remove: false,
        rotation: false,
        size: false,
        wals: false,
      },
      rotation: 0,
      type: 'Piece',
      uuid: '9a15f220-00dc-11f0-af54-89c0197358c6',
      version: 1,
      wals: [],
      width: 30,
      x: -136.5,
      y: -79,
      z: 44,
    },
  ],
  fromPreset: null,
  icon: '🔴',
  isArchived: false,
  isDeleted: false,
  isLibraryItem: true,
  isStewarded: false,
  lastChangeAt: 1741960808897,
  name: 'Checkers',
  notificationsConfigOverride: {},
  playersSlots: [
    {
      color: '#222222',
      pubKey: null,
    },
    {
      color: 'hsl(0, 60%, 50%)',
      pubKey: null,
    },
  ],
  version: 9,
  wals: [],
} as const satisfies GameSpace;
