import type { GameSpace } from '../types';

export default {
  creator: '',
  elements: [
    {
      height: 614,
      lock: {
        config: false,
        position: false,
        remove: false,
        rotation: false,
        size: false,
        wals: false,
      },
      rotation: 0,
      type: 'Image',
      url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9b/Blank_Go_board.svg/600px-Blank_Go_board.svg.png?20140621020717',
      uuid: 'c41c01f0-a037-11ef-8b06-8597ca08db5f',
      version: 1,
      wals: [],
      width: 614,
      x: 0,
      y: 0,
      z: 1,
    },
    {
      height: 250,
      lock: {
        config: false,
        position: false,
        remove: false,
        rotation: false,
        size: false,
        wals: false,
      },
      rotation: 0,
      showTimers: true,
      turnsLog: [],
      type: 'TurnTracker',
      uuid: 'b5ec7f90-a039-11ef-8b06-8597ca08db5f',
      version: 1,
      wals: [],
      width: 200,
      x: 412.9343991179714,
      y: -3.872105843439897,
      z: 36,
    },
    {
      createdPieces: [],
      display: {
        mode: 'emoji',
        value: '⚪️',
      },
      height: 164,
      limit: 181,
      lock: {
        config: true,
        position: true,
        remove: true,
        rotation: true,
        size: true,
        wals: true,
      },
      pieceH: 30,
      pieceW: 30,
      rotation: 0,
      type: 'PieceSource',
      uuid: '9efc9960-a11e-11ef-bec7-c5b65c84efe4',
      version: 2,
      wals: [],
      width: 162,
      x: -389.5,
      y: -83,
      z: 37,
    },
    {
      createdPieces: ['ccc5a350-a11e-11ef-bec7-c5b65c84efe4'],
      display: {
        mode: 'emoji',
        value: '⚫️',
      },
      height: 166,
      limit: 180,
      lock: {
        config: true,
        position: true,
        remove: true,
        rotation: true,
        size: true,
        wals: true,
      },
      pieceH: 30,
      pieceW: 30,
      rotation: 0,
      type: 'PieceSource',
      uuid: 'a0610b60-a11e-11ef-bec7-c5b65c84efe4',
      version: 2,
      wals: [],
      width: 166,
      x: -390.5,
      y: 86,
      z: 38,
    },
    {
      display: {
        mode: 'emoji',
        value: '⚫️',
      },
      height: 30,
      lock: {
        config: true,
        position: false,
        remove: false,
        rotation: false,
        size: false,
        wals: false,
      },
      rotation: 0,
      type: 'Piece',
      uuid: 'ccc5a350-a11e-11ef-bec7-c5b65c84efe4',
      version: 1,
      wals: [],
      width: 30,
      x: -424.5,
      y: 35,
      z: 40,
    },
  ],
  isStewarded: false,
  lastChangeAt: 1731434024355,
  minMaxPlayers: [2, 2],
  name: 'Go',
  players: [],
  status: 'library',
  version: 4,
  wals: [],
} as const satisfies GameSpace;
