[package]
edition = "2021"
name = "gamez"
version = "0.0.2"

[lib]
crate-type = ["cdylib", "rlib"]
name = "gamez"

[dependencies]
hdk = { workspace = true }
serde = { workspace = true }
gamez_integrity = { workspace = true } 
holochain_integrity_types = {workspace = true}