[package]
edition = "2021"
name = "gamez_integrity"
version = "0.0.2"

[lib]
crate-type = ["cdylib", "rlib"]
name = "gamez_integrity"

[dependencies]
hdi = { workspace = true }
serde = { workspace = true }
holochain_integrity_types = {workspace = true}